// Client-side glossary export — runs entirely off the already-bundled
// glossary data, no backend round-trip needed (unlike scan contract export,
// which depends on a specific scan_id living in the API's in-memory store).

import { GLOSSARY, type GlossaryEntry } from '../data/glossary';

const KIND_LABELS: Record<GlossaryEntry['kind'], string> = {
  drift_class: 'Drift Class',
  stabilisation_operator: 'Stabilisation Operator',
  compound_mode: 'Compound Drift Mode',
  concept: 'Concept',
};

function yamlEscape(text: string): string {
  return text.replace(/"/g, '\\"').replace(/\n/g, '\\n');
}

export function glossaryToYaml(entries: GlossaryEntry[] = GLOSSARY): string {
  const lines: string[] = [
    '# ═══════════════════════════════════════════════════════════════',
    '# X-VERBA GLOSSARY',
    '# Drift Classes, Stabilisation Operators, Compound Drift Modes and',
    '# core concepts. Source: Paper 5 (Balasubramanian, 2026) + X-VERBA docs.',
    '# ═══════════════════════════════════════════════════════════════',
    '',
    'terms:',
  ];
  for (const e of entries) {
    lines.push(`  - id: "${e.id}"`);
    lines.push(`    kind: "${KIND_LABELS[e.kind]}"`);
    lines.push(`    term: "${yamlEscape(e.term)}"`);
    if (e.tier) lines.push(`    tier: "${e.tier}"`);
    if (e.category) lines.push(`    category: "${e.category}"`);
    lines.push(`    short_definition: "${yamlEscape(e.shortDefinition)}"`);
    lines.push(`    definition: "${yamlEscape(e.definition)}"`);
    if (e.example) lines.push(`    example: "${yamlEscape(e.example)}"`);
    if (e.relatedTerms && e.relatedTerms.length > 0) {
      lines.push(`    related_terms: [${e.relatedTerms.map((t) => `"${t}"`).join(', ')}]`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

export function glossaryToJson(entries: GlossaryEntry[] = GLOSSARY): string {
  return JSON.stringify(entries, null, 2);
}

export function glossaryToTxt(entries: GlossaryEntry[] = GLOSSARY): string {
  const lines: string[] = ['X-VERBA GLOSSARY', '='.repeat(60), ''];
  for (const e of entries) {
    lines.push(`${e.term}  [${KIND_LABELS[e.kind]}${e.tier ? `, Tier ${e.tier}` : ''}]`);
    lines.push('-'.repeat(40));
    lines.push(e.definition);
    if (e.example) lines.push(`\nExample: ${e.example}`);
    if (e.relatedTerms && e.relatedTerms.length > 0) {
      lines.push(`\nRelated: ${e.relatedTerms.join(', ')}`);
    }
    lines.push('', '');
  }
  return lines.join('\n');
}

export function glossaryToMd(entries: GlossaryEntry[] = GLOSSARY): string {
  const lines: string[] = ['# X-VERBA Glossary', ''];
  let currentKind: string | null = null;
  for (const e of entries) {
    if (KIND_LABELS[e.kind] !== currentKind) {
      currentKind = KIND_LABELS[e.kind];
      lines.push(`## ${currentKind}s`, '');
    }
    lines.push(`### ${e.term}${e.tier ? ` — Tier ${e.tier}` : ''}`, '');
    lines.push(e.definition, '');
    if (e.example) lines.push(`> ${e.example}`, '');
    if (e.relatedTerms && e.relatedTerms.length > 0) {
      lines.push(`**Related:** ${e.relatedTerms.map((t) => `\`${t}\``).join(', ')}`, '');
    }
  }
  lines.push('---', '_Generated by X-VERBA — Super Semantics_');
  return lines.join('\n');
}

export function downloadText(content: string, filename: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
