import express from 'express';
import cors from 'cors';
import { runScan } from './scanner.js';
import { saveScan, getScan, getHistory } from './db.js';

const app = express();
const PORT = parseInt(process.env.PORT || '3001', 10);

app.use(cors());
app.use(express.json());

// ── POST /api/scan ───────────────────────────────────────────────────────────
app.post('/api/scan', async (req, res) => {
  const { repo_url } = req.body;

  if (!repo_url || typeof repo_url !== 'string') {
    res.status(400).json({ error: 'repo_url is required' });
    return;
  }

  // Basic URL validation
  const urlPattern = /^https?:\/\/(www\.)?github\.com\/[^/]+\/[^/]+/i;
  if (!urlPattern.test(repo_url)) {
    res.status(400).json({ error: 'Invalid GitHub repository URL' });
    return;
  }

  try {
    const result = await runScan(repo_url);
    saveScan(result);
    res.json(result);
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Scan failed';
    res.status(500).json({ error: message });
  }
});

// ── GET /api/contract/:scan_id ───────────────────────────────────────────────
app.get('/api/contract/:scan_id', (req, res) => {
  const scan = getScan(req.params.scan_id);
  if (!scan) {
    res.status(404).json({ error: 'Scan not found' });
    return;
  }

  // Generate a governance.yaml contract from scan results
  const yaml = generateContractYaml(scan);
  res.type('text/yaml').send(yaml);
});

// ── GET /api/scans/:repo ─────────────────────────────────────────────────────
app.get('/api/scans/:repo', (req, res) => {
  const history = getHistory(decodeURIComponent(req.params.repo));
  res.json(history);
});

// ── Health check ─────────────────────────────────────────────────────────────
app.get('/api/health', (_req, res) => {
  res.json({ status: 'ok', version: '0.1.0' });
});

app.listen(PORT, () => {
  console.log(`X-VERBA API running on http://localhost:${PORT}`);
});

// ── YAML contract generator ──────────────────────────────────────────────────

function generateContractYaml(scan: ReturnType<typeof getScan>): string {
  if (!scan) return '# No scan data';

  const lines: string[] = [
    '# ═══════════════════════════════════════════════════════════════',
    '# X-VERBA GOVERNANCE CONTRACT',
    '# Generated by Super Semantics — supersemantics.org',
    '#',
    '# HOW TO USE THIS FILE',
    '#',
    '# This is your system\'s governance contract.',
    '# X-Verba scanned your code and found the decision points.',
    '# Your job is to fill in every field marked: null',
    '# ═══════════════════════════════════════════════════════════════',
    '',
    'system_identity:',
    `  identity_key: "${scan.scan_id}"`,
    `  system_name: "${scan.repo_name}"`,
    `  scan_date: "${scan.scan_date}"`,
    '  verba_version: "0.2.0"',
    '  reviewed: false',
    '  approved: false',
    '',
    'governance_score:',
    `  structural_gamma: ${scan.gamma}`,
    `  status: "${scan.gamma_status}"`,
    `  total_ungoverned_nodes: ${scan.ungoverned_nodes.length}`,
    `  files_affected: ${scan.files_affected}`,
    '',
    '# ── NODES ──────────────────────────────────────────────────────',
    '# Each node is a point where your system makes a consequential decision.',
    '',
    'nodes:',
  ];

  for (const node of scan.ungoverned_nodes) {
    lines.push(`  - id: "${node.drift_class}-${node.line}"`);
    lines.push(`    location: "${node.file}:${node.line}"`);
    lines.push(`    drift_class: "${node.drift_class}"`);
    lines.push(`    severity: "${node.severity}"`);
    lines.push(`    issue: "${node.issue}"`);
    lines.push(`    recommendation: "${node.recommendation}"`);
    lines.push('    pre_node:');
    lines.push('      conditions_for_execution: null  # Fill: what must be TRUE to proceed');
    lines.push('      conditions_to_block: null       # Fill: what must BLOCK execution');
    lines.push('      fallback: null                   # Fill: what happens if blocked');
    lines.push('');
  }

  lines.push('# ── DRIFT CLASS SUMMARY ─────────────────────────────────────────');
  lines.push('drift_classes:');
  for (const [code, count] of Object.entries(scan.drift_class_summary)) {
    lines.push(`  ${code}: ${count}`);
  }

  return lines.join('\n');
}
